on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  npm-publish:
    name: Publish Latest to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          registry: https://registry.npmjs.org/
          package: package.json
